lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  nonscript: false
kramadown:
  math_engine: mathjax
  syntax_highlighter: rouge

# theme: jekyll-theme-minimal

remote_theme: pages-themes/@dinky@v0.2.0
title: JRSMoura's Portifolio
description: Keep up for my projects and texts
