---
layout: post
title: Blogging Like a Hacker
---

lsi: false
safe: true
incremental: false
source: https://github.com/jrsmoura/jrsmoura.github.io
highlighter: rouge
gist:
  nonscript: false
kramadown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-minimal
title: JRSMoura's homepage
description: Keep up for my projects