lsi: false
safe: true
incremental: false
source: https://github.com/jrsmoura/jrsmoura.github.io
highlighter: rouge
gist:
  nonscript: false
kramadown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: minima
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme  
title: JRSMoura's Homepage
description: Keep up for my projects